// <auto-generated />
namespace CargoManagementDataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class addedalltables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedalltables));
        
        string IMigrationMetadata.Id
        {
            get { return "202412161451352_added-all-tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
